function AADIcal = rdAADI(filename, dataLines)
%IMPORTFILE Import data from a text file
%  AADICAL = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  AADICAL = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  AADIcal = importfile("/Users/samuelstevens/Dropbox/Hakai/gliders/cal_certs/AADI_cal.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Oct-2024 12:10:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SerialNumber", "CalibrationDate", "SVUfoilCoef_0", "SVUfoilCoef_1", "SVUfoilCoef_2", "SVUfoilCoef_3", "SVUfoilCoef_4", "SVUfoilCoef_5", "SVUfoilCoef_6"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "CalibrationDate", "InputFormat", "dd.MM.yyyy", "DatetimeFormat", "preserveinput");

% Import the data
AADIcal = readtable(filename, opts);

end