function ARODcal = rdAROD(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ARODCAL = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  ARODCAL = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  ARODcal = importfile("/Users/samuelstevens/Dropbox/Hakai/gliders/cal_certs/AROD_cal.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Oct-2024 10:03:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Model", "SerialNumber", "CalibrationDate", "Cp", "d0", "d1", "d2", "d3", "d4", "c0", "c1", "c2", "e0"];
opts.VariableTypes = ["categorical", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Model", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "CalibrationDate", "InputFormat", "yyyy-MM-dd", "DatetimeFormat", "preserveinput");

% Import the data
ARODcal = readtable(filename, opts);

end